include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - '**.freezed.dart'
    - '**.g.dart'
    - '**.gr.dart'
    - '**/generated_plugin_registrant.dart'

linter:
  rules:
    public_member_api_docs: false
    sort_pub_dependencies: false
    flutter_style_todos: false
    one_member_abstracts: false 