/// Flutter icons AppIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIcons
///      fonts:
///       - asset: fonts/AppIcons.ttf
///
///
///
library;

import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'AppIcons';

  static const IconData settings = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData home = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData version = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData privacypolicy = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData termsofuse = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData share = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData rate = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData info = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData arrowupright = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData close = IconData(0xe809, fontFamily: _kFontFam);
}
